//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShelf.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class BookShelf
    {
        [HiddenInput(DisplayValue = false)]
        public int BookId { get; set; }
        [Required]
        [Display(Name = "Название")]
        public string BookName { get; set; }
        [Required]
        [Display(Name = "Автор")]
        public string BookAuthor { get; set; }
    }
}
